### ISSUE TITLE
date cannot be nil / and resizing

### ISSUE THREAD

**Issue by bdk529** [MosheBerman/MBCalendarKit#111]
Is there an option for resizing CKCalendarView?

Also, the first call to setMinimumDate / setMaximumDate generates a bunch of messages like below.  Once one is set, the other is ok, so I assume it's an issue while trying to compare the dates when one is still nil:

**\* -[__NSCFCalendar components:fromDate:]: date cannot be nil
Future exception.
A few of these errors are going to be reported with this complaint, then further violations will simply be ignored.
Here is the backtrace where this occurred this time (some frames may be missing due to compiler optimizations):

**Comment by MosheBerman** [comment]
How do you want to resize?

Because this code was originally written before autolayout, there are some quirks with resizing, but there was another issue requesting iPad support. It might have more information in that regard. 

CalendarKit supports 3 modes, each with a different size. If you're using the calendar view, instead of the calendar view controller, you can resize with the various modes.

As far as the logs, I suspect that you are right. I'll look into that, but the behavior is inconsequential, at least on the latest public iOS. 

Thanks again!

**Comment by bdk529** [comment]
Thanks.  Agree logs are mostly just a nuisance.  Just a pain when it conceals real log messages.

For resizing - when I rotate an iPad, the calendar spills over the bottom of the screen.  I am using a CKCalendarView in month mode, which I put underneath a UIDatePicker (to set the time).  For now, I'll try to lock this screen, so that it can only be viewed in portrait.  Ideally, I would like to be able to apply a scale factor instead - it's ok if both the heigh and width shrink proportionally.  The logic for this must be there, since the calendar appears to scale based on the device, but is it exposed to users?

**Comment by MosheBerman** [comment]
This thread is old, but MBCalendarKit just hit version 5.0.0 today, and it includes auto layout support and nullability modifiers. I've also done some work on the framework that should minimize the logging spew, so give it a shot and report back. Because this issue is so old, I'm going to close it, and you can feel free to re-open if necessary.
