### ISSUE TITLE
Disable dragging on CustomCellProviding

### ISSUE THREAD

**Issue by MaorS** [MosheBerman/MBCalendarKit#128]
# Summary

How can I disable the dragging option on CustomCellProviding?

![gif](https://user-images.githubusercontent.com/20594674/29968155-06d89ad6-8f23-11e7-8d11-0cf27c7733f7.gif)

**Comment by MosheBerman** [comment]
Are you talking about the scrubbing that makes the selection follow your finger?

**Comment by MaorS** [comment]
Yes, after I drag in the calendar the gray circle shows the selected day.
then when I click on a different day it select a random day and paint it gray

**Comment by MosheBerman** [comment]
Ah, I've seen that. It's a byproduct of cell recycling. You need to manually set each cell's background color when customizing. 

What's happening is that as you scrub, the cell under your "finger" (the cursor) is being selected. When you finish the selection, the calendar view updates the selection, and the internal collection view recycles all of the cells. 

If you don't set the color on every cell, the last highlighted one is going to stay highlighted, and show up somewhere, wherever the collection view puts it. The calendar view doesn't handle this automatically, because it can't really tell what your default appearance is when customizing. 

Does this help point you in the right direction?

**Comment by MaorS** [comment]
Yes, thanks!

**Comment by MosheBerman** [comment]
Awesome, so is it safe to close this issue?
