### ISSUE TITLE
MBCalendarKit-Swift.h not found

### ISSUE THREAD

**Issue by rounak** [MosheBerman/MBCalendarKit#64]
I get a 'MBCalendarKit-Swift.h' file not found error when trying to run the xcode project.

**Comment by MosheBerman** [comment]
This file is automatically generated by Xcode on build. You should try these steps: 

1. Clean build. (Command + Shift + K)
2. Build (Command + B)
3. Run (Command + R)

Let me know how these steps work out for you.

**Comment by gblotter** [comment]
Same issue... doing a Clean, then Build doesn't resolve the problem

**Comment by ServicePal** [comment]
Same issue here. Would love to try your code.

**Comment by MosheBerman** [comment]
So this has to do with Swift's modules. Depending on how your project is configured, your "Project-Swift.h" will be different. I haven't read up extensively on third party library integration with Swift and Objective-C, but the generated Swift header should have the same name as the project, if you're including the basic sample code.

Apple has [wonderful documentation on "Mix and Match,"](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) which seems to be what they're calling language interoperability.

On my system, I'm able to build and run my project with the Swift demo, and I include MBCalendarKit-Swift.h because the target is called `MBCalendarKit`. If you were making a new calendar app  called `MyAwesomeCalendar`, *and compiling MBCalendarKit as part of the same target* you would need to import `MyAwesomeCalendar-Swift.h`.

I'm not sure how to include a compiled Swift framework into Objective-C, but the only part of MBCalendarKit that is actually written in Swift is the demo view controller. The Objective-C version is still there, and you can just delete the MBCalendarKit-Swift.h import and replace the word "Swift" on line 28 with "CK" and you'll get the Objective-C version.

Specifically, replace this: 

````objective-c
self.viewController = [SwiftDemoViewController new];
````

with this:

```objective-c
self.viewController = [CKDemoViewController new];
````

Swift is still relatively new, so thanks for reporting the issues and bearing with me as we learn how this works together.

If you're still reading, I would appreciate if you could share screenshots so I can get an idea of exactly what you're trying to do and if you're running the demo app or a custom one that you're working on integrating MBCalendarKit with.

Thanks so much!

**Comment by MosheBerman** [comment]
Try the latest release. The swift demo is disabled by default, so the swift header is commented out. Let me know if 3.0.5 runs for you.

**Comment by ServicePal** [comment]
Works now. You can mark the issue resolved. Thanks Moshe.

**Comment by MosheBerman** [comment]
Excellent, thanks.

**Comment by dev-ajmehra** [comment]
swift demo not working
