### ISSUE TITLE
我有一个问题

### ISSUE THREAD

**Issue by Coolzhou** [MosheBerman/MBCalendarKit#71]
你好，我在选择日期后 ，在 CKDemoViewController.m 文件中，

```
- (void)calendarView:(CKCalendarView *)CalendarView didSelectDate:(NSDate *)date
{
    NSLog(@"date =%@",date);
}
```

打印出来的日期和实际日期不相同，请问是什么问题

**Comment by Mirzhou** [comment]
I clicked today print today's date, print the results as follows:
2015-03-03 15: 24: 08.152 Communication [4822: 2027576] date = 2015-03-02 16:00:00 +0000
But, today's date is 2015-03-03 15: 24: 08.152

**Comment by Mirzhou** [comment]
还有一个问题希望得到解答，也是在 CKDemoViewController.m 文件中，我想添加事件数据源，但数据多的话，以下方法比较麻烦，请问有更高效的方法吗？
   /**
     *  Add the events to the data source.添加事件数据源
     *  The key is the date that the array of events appears on.关键是事件的阵列上出现的日期
     */ 
    self.data[date] = @[releaseUpdatedCalendarKit,even];
    self.data[date2] = @[mockingJay, integrationEvent];
    self.data[date3] = @[fixBug];

**Comment by MosheBerman** [comment]
I don't speak Chinese, so I apologize in advance if I misunderstand your questions. (I used Google Translate and your sample code to try and come up with a reasonable response.)

The mismatched dates *looks* like a time zone issue, but the minutes and seconds are probably being reset by the calendar kit.

As for keying events in the data source method, have a look at the methods in `NSCalendar+DateComparison.h` and `NSCalendar+Components.h` and simplify the dates so that you can compare without accounting for minutes and seconds.

Hope this helps.

**Comment by Mirzhou** [comment]
Thank you for your reply, I am a beginner iOS. My English is not good, did not say clearly. I want to ask is, if many of the data, the following add data event is very troublesome, how more efficient, thank you!
self.data[date] = @[releaseUpdatedCalendarKit,even];
self.data[date2] = @[mockingJay, integrationEvent];
self.data[date3] = @[fixBug];
self.data[date4] = @[releaseUpdatedCalendarKit,even，fixBug];
self.data[date5] = @[mockingJay, integrationEvent];
self.data[date6] = @[fixBug];

**Comment by Mirzhou** [comment]
Add after the event, the calendar on the point is how to refresh? In the CKDemoViewController.m file, how to refresh the data source events？

Thank you very much。

**Comment by MosheBerman** [comment]
Sorry for the late reply - 

- I agree that there should probably be better event management, but it's a problem I haven't even begun to think about.
- The calendar view has a method called `- reloadAnimated:`.  (Or `- reload` if you don't need to dynamically decide animation and are ok with immediate refresh.)
