### ISSUE TITLE
Customizing colors?

### ISSUE THREAD

**Issue by seenickcode** [MosheBerman/MBCalendarKit#83]
I see that you are customizing the colors via #define statements but is there a way to override those with your own?  I tried #undef and that didnt' work. Thanks.

**Comment by MosheBerman** [comment]
Can't you just replace the `#define`d colors with your own?

**Comment by MosheBerman** [comment]
Alternatively, look at the `UIAppearance` support on the cell views.

**Comment by seenickcode** [comment]
Yeah I tried to override the #define statements with no luck.  

UIAppearance works but not exactly for all situations.

I forked the repo and may suggest some changes on how this calendar can be customized.  But before I do that, do you think there is a better way to customize the entire calendar?  For example, making the header style more like iOS 8 (less gray, no gradients), and also customizing the cells to look more like iOS 8 (white, no gray).  

One idea is to instantiate the entire calendar with a single config struct or dict and pass that around to internal components like header.

lmk your thoughts.

thanks.

**Comment by seenickcode** [comment]
Scratch that.  You're right, overriding those macros makes the most sense.   Yet I still have to figure out a way users can override them easily, as during compilation, the macros in the library take precedence.

Take a look at my fork if you're interested.  I'll submit a pull request soon if you don't have any comments.

https://github.com/seenickcode/MBCalendarKit

**Comment by MosheBerman** [comment]
It's been so long since I built that so I don't recall why I did it with the macros. In retrospect, it make sense  to change those to default values and allows developers to set properties.

Let's see what you come up with.

**Comment by seenickcode** [comment]
Ok I committed something now.  I didn't do much, just renamed some of the macros and added support for nil colors (to disable things like shadows).

We should discuss more before I send a pull request:   The problem I'm still having is it seems you can't really override (#undef then #define again) macros from another Pod header file.  My temporary solution is ``pod update`` then manually paste in my macros by editing your .h files directly (ghetto, I know).

**Comment by MosheBerman** [comment]
Does PR #89  do the trick?

**Comment by MosheBerman** [comment]
## A More Modern Approach To Custom Cells

In the next version MBCalendarKit, I'm actually adding API to allow consumers of the API (i.e. developers like you and me) to get direct access to the calendar cell before it's displayed, along with information about what the cell is going to display, for purposes of customization.

Before discussing the new API, here's a little background on the current implementation I think is helpful:

In MBCalendarKit, a calendar cell is typically used to represent a date on a calendar system. It may represent the current calendar date (i.e. where planet Earth is along its path around the sun) or a user selected date. (i.e. when the user taps on a different date to select it.)  The calendar view also supports clamping its contents to within an open or closed date range. Cells might be highlighted ("selected") or not ("deselected.") We may be in the month mode, or one of the other supported modes, etc... 

The combination of all of these factors gives us a set of several possible contexts or "states" that a cell can be used in. When I initially wrote `MBCalendarKit`, these were expressed as an enum, and each cell had a property and several methods to configure display according to the state of the cell. 

In 4.0.1 and earlier, `CKCalendarView` had an internal cell recycling mechanism, and it would manage the states on the cells as the user interacted with the control. One of the tricky design goals here is to continue to express these states while still allowing complete control and flexibility over the cells' appearance.

> As an aside: Some of these "states" are somewhat tied to the semantics of a scrubbable calendar UI, a la iOS 6 and earlier, but they're still useful even in the world of gesture based scrolling calendars, like the more modern iOS 7+ calendar app, so `MBCalendarKit` is keeping them.

Beyond colors and states, a truly customizable calendar library would also offer some kind of default behavior, so that a consumer of the framework could just drop it in, wire up the data source and delegate, and go. The quickest way to do this is to maintain backwards compatibility internally and design the new API to work alongside the old design. 

So, let's consider all of this as we talk about the new API. 

## @protocol CKCustomCellProviding : (WIP)

The new API few parts: 

- A protocol called `CKCustomCellProviding` for providing the custom cell class and configuring instances of it.
- A property on `CKCalendarView` for connecting your cell customization code with the calendar view.
- A method on `CKCalendarView` to manually register your custom cell class, if you want to change it at runtime.
- A default implementation of `CKCustomCellProviding`, built into `CKCalendarView`, so that the calendar continues to function in a backwards compatible way. 

This is still a work in progress, as I want to get just the right balance between flexibility and ability to depend on the framework to do the heavy lifting.

## Designing the Cell Design API 

Let's start with the `CKCustomCellProviding` protocol. It has two parts: 

1. A property called `customCellClass` which your custom cell provider implements, to return a class that is used for the custom cells. 
2. A method called `calendarView:willDisplayCell:withContext:`. The last parameter is still in flux as of this writing. We'll get back to this in a little bit.

The `CKCalendarView` class needs a few changes to support this new behavior. So, the `CKCalendarView` class gets a new property called `customCellProvider`, and a new method called `registerCellClass:`. 

Setting the `customCellProvider` causes the calendar view to automatically ask the provider for its custom cell class, via the property mentioned above. If later on at runtime you decide to change the class for some reason, or if you just want to subclass the default calendar cell without doing complex customization at display-time, you can call `registerCellClass:` with your own class. 

## Open Questions

I'm still trying to figure out the exact relationship between the custom cell class and the default cell implementation. i.e. Is this a subclass of the default cell class? A sibling of a common superclass? Just a plain old `UICollectionViewCell` subclass?

What context does a custom cell provider want, and what does it not care about? How much UI should the defaults provide, before it becomes difficult to customize? What is too little default UI?

The final piece of this puzzle is really how to set this up so that the default implementation remains the same, and that customization is flexible, without having to rely on consumers of the framework to spending time doing extra work to figure out what the cell needs to display.

## Getting It Right

While building this out, I've gone through several iterations of `calendarView:willDisplayCell:forDate:` method, to address several concerns I've had with other calendar libraries when trying to customize cell contents.

The first implementation looked like this: 

```obj-c
-(void) calendarView:(CKCalendarView *)calendar willDisplayCell:(CKCalendarCell *)cell forDate:(NSDate *)date;
```

Notice that the cell is a `CKCalendarCell *` instance, which is the default cell class. With this API design, we can configure the cell *after* the calendar view has gotten to it. This means that we can't safely remove any of the default subviews, such as the dot or the label. We also don't have so much information about the cell's context, so it might be unclear how we might want to style our own custom subviews.
 
The second pass was to change the `CKCalendarCell` to a vanilla `UICollectionViewCell`:

```obj-c
- (void)calendarView:(CKCalendarView *)calendar willDisplayCell:(UICollectionViewCell *)cell forDate:(NSDate *)date;
```

This is a little better, but we still don't have the context. Is this cell out of scope for the month or week? Does it represent an un-selectable date that was clamped by the calendar view's `minimumDate` or maximumDate`? Also, now we have to cast back to `CKCalendarCell`  just to customize the cell.

The third iteration moves in the direction of adding some of those contextual properties:

```obj-c
- (void)calendarView:(CKCalendarView *)calendar willDisplayCell:(UICollectionViewCell *)cell forDate:(NSDate *)date isToday:(BOOL)isToday isThisMonth:(BOOL)thisMonth isOutOfRange:(BOOL)isOutOfRange;
```

This is better, but the first thing you may notice is just how many arguments this method takes. It's verbose enough, being `Objective-C` (or Objective-C inspired, if you're using Swift) and adding the three or flags is a bit much. Also, what happens if we want to add even more context? Do we add more fields to the method? Um... I'd rather not do that.

One classic approach to this problem is to pass in an `NSDictionary *` for this final argument and let users pick out the parts that they want. The trouble is that `BOOL` variables are values, not objects, so `NSDictionary` won't accept them on their own. Boxing syntax is nice, but a custom class avoids passing string keys, and gives more concrete documentation. 

So the next iteration of this protocol method added a class called `CKCalendarContext *` and it looks like this:

```obj-c
- (void)calendarView:(nonnull CKCalendarView *)calendarView willDisplayCell:(nonnull UICollectionViewCell *)cell forDate:(nonnull NSDate *)date withContext:(nonnull CKCalendarCellContext *)context;
```

The context class has some interesting properties on it. It has the state, and the boolean flags we discussed.  **This is where we are now on the develop branch.** I think a few more changes would be helpful.

The date itself is part of the context. Moving it into the context class would simplify the API and make it clear that all of the information necessary to configure the cell is in `CKCalendarCellContext`. 

Finally, by tweaking the class hierarchy of the default cell just a little bit, it may be possible to get really nice default behavior while still allowing for the flexibility of completely custom cell design.

**Comment by MosheBerman** [comment]
This is covered in 5.0.0. Short answer: You can use the Custom Cell Provider API. 

Since this is an old issue, I'm going to close this.
